# Generated by Django 5.2.4 on 2025-12-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('showtime', models.TimeField()),
                ('ticket', models.PositiveIntegerField()),
            ],
        ),
    ]
