# Generated by Django 5.2.4 on 2025-12-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('movie', models.CharField(max_length=7)),
                ('dob', models.DateField()),
                ('time', models.TimeField()),
                ('ticket', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
