# Generated by Django 5.2.4 on 2025-12-31 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='email',
            field=models.EmailField(default='kamanisanju2705@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
