# Generated by Django 5.2.4 on 2025-12-20 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ticket_delete_booking_delete_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='dob',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='movie',
            new_name='movie_name',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='time',
            new_name='showtime',
        ),
    ]
