# Generated by Django 5.2.4 on 2025-12-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_dob_ticket_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='movie_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
